import { PrismaClient, PlantCategory, Season } from '@prisma/client'

const prisma = new PrismaClient()

const plants = [
  // ── LEGUMES / HORTALIÇAS ──────────────────────────────────────────────────
  {
    name: 'Alface',
    scientificName: 'Lactuca sativa',
    emoji: '🥬',
    description: 'A alface é uma das hortaliças folhosas mais populares do Brasil, perfeita para saladas frescas. Adapta-se bem a vasos e pequenos espaços, sendo ideal para hortas domésticas e urbanas.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 45,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Evite plantar no verão intenso pois pode espigrar. Em locais quentes, prefira sombra parcial durante o calor do dia.',
  },
  {
    name: 'Cenoura',
    scientificName: 'Daucus carota',
    emoji: '🥕',
    description: 'A cenoura é uma raiz tuberosa rica em betacaroteno, fibras e vitaminas do complexo B. Prefere climas frescos e solo arenoso e profundo para o desenvolvimento correto da raiz.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 70,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'O solo deve ser fofo e destorroado para a raiz crescer reta. Nunca use adubo orgânico fresco — bifurca e deforma as raízes.',
  },
  {
    name: 'Pimentão',
    scientificName: 'Capsicum annuum',
    emoji: '🫑',
    description: 'O pimentão é um fruto versátil disponível nas variedades verde, vermelha, amarela e laranja. Muito usado na culinária brasileira em refogados, saladas e recheios.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 90,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Instale suportes quando a planta estiver carregada de frutos. Adube com fertilizante rico em potássio durante o florescimento.',
  },
  {
    name: 'Cebola',
    scientificName: 'Allium cepa',
    emoji: '🧅',
    description: 'A cebola é um bulbo indispensável na culinária brasileira e mundial. Rica em quercetina e compostos sulfurosos que contribuem para a saúde cardiovascular.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 120,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Reduza a irrigação quando as folhas começarem a tombar — sinal de maturidade. Cure os bulbos ao sol por 2-3 semanas antes de armazenar.',
  },
  {
    name: 'Pepino',
    scientificName: 'Cucumis sativus',
    emoji: '🥒',
    description: 'O pepino é um fruto refrescante com alto teor de água, versátil na culinária. De cultivo relativamente rápido e produtivo, é ideal para hortas domésticas.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 55,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Treine as ramas em varal ou cerca para economizar espaço. Colha regularmente para estimular a produção contínua.',
  },
  {
    name: 'Espinafre',
    scientificName: 'Spinacia oleracea',
    emoji: '🥬',
    description: 'O espinafre é uma folhosa rica em ferro, cálcio, magnésio e vitaminas A e C. Prefere temperaturas amenas, sendo perfeito para cultivo nos meses mais frios.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 45,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Colha as folhas externas primeiro para estimular brotamento contínuo. Evite plantio sob altas temperaturas.',
  },
  {
    name: 'Rúcula',
    scientificName: 'Eruca vesicaria',
    emoji: '🌿',
    description: 'A rúcula tem sabor picante e levemente amargo que enriquece saladas e coberturas de pizza. É uma das hortaliças de ciclo mais curto.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 35,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Faça plantios escalonados a cada 2-3 semanas para colheitas contínuas. No calor intenso espiga rápido e fica excessivamente amarga.',
  },
  {
    name: 'Brócolis',
    scientificName: 'Brassica oleracea var. italica',
    emoji: '🥦',
    description: 'O brócolis é uma crucífera nutritiva rica em vitaminas C e K, fibras e compostos antioxidantes. Prefere climas frescos e é um dos vegetais mais indicados para a saúde.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 80,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Colha a cabeça central quando ainda compacta e firme. Após a colheita principal, os brotos laterais continuam produzindo por semanas.',
  },
  {
    name: 'Couve-flor',
    scientificName: 'Brassica oleracea var. botrytis',
    emoji: '🤍',
    description: 'A couve-flor é uma crucífera de sabor delicado, muito versátil na cozinha. Exige cuidados especiais de temperatura e umidade para formar a cabeça branca compacta.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 90,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Dobre as folhas externas sobre a cabeça branca para protegê-la do sol e manter sua cor clara. Colha antes de abrir e amarelecer.',
  },
  {
    name: 'Repolho',
    scientificName: 'Brassica oleracea var. capitata',
    emoji: '🥬',
    description: 'O repolho é uma hortaliça resistente e nutritiva, rica em vitamina C e fibras. Muito usado em saladas cruas, refogados, sopas e na fermentação do chucrute.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 90,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Pressione levemente a cabeça para verificar a firmeza antes de colher. Plantas muito espaçadas formam cabeças maiores.',
  },
  {
    name: 'Beterraba',
    scientificName: 'Beta vulgaris',
    emoji: '🟣',
    description: 'A beterraba é uma raiz de cor vermelho-arroxeada intensa, rica em folato, manganês e nitratos naturais que melhoram o desempenho físico e a pressão arterial.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 60,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'As folhas também são comestíveis e nutritivas! Colha quando os ombros da raiz estiverem visíveis acima do solo, com 5-8 cm de diâmetro.',
  },
  {
    name: 'Abobrinha',
    scientificName: 'Cucurbita pepo',
    emoji: '🥒',
    description: 'A abobrinha é um fruto de crescimento rápido e alta produtividade, muito versátil na culinária. Pode ser consumida crua, grelhada, assada ou em sopas.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 50,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Colha os frutos jovens (15-20 cm) para melhor sabor e para estimular nova produção. Plantas maduras produzem frutos enormes e de sabor menos delicado.',
  },
  {
    name: 'Vagem',
    scientificName: 'Phaseolus vulgaris',
    emoji: '🫘',
    description: 'A vagem é uma leguminosa muito apreciada na culinária brasileira. Além dos vagens tenras, os grãos maduros são usados como feijão. Rica em proteínas e fibras.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 55,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Colha as vagens ainda imaturas e macias para consumo fresco. Se deixar passar do ponto, os grãos endurecem. Existe versão trepadeira e de arbusto.',
  },
  {
    name: 'Rabanete',
    scientificName: 'Raphanus sativus',
    emoji: '🔴',
    description: 'O rabanete é uma das hortaliças de ciclo mais rápido do mundo — 25 dias da semente à colheita! Sabor levemente picante, crocante e refrescante em saladas.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 25,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Colha imediatamente quando atingir 2-3 cm para evitar que fique oco e muito picante. Excelente para ensinar crianças sobre jardinagem pelo ciclo ultra-rápido.',
  },
  {
    name: 'Nabo',
    scientificName: 'Brassica rapa',
    emoji: '⚪',
    description: 'O nabo é uma raiz de sabor adocicado quando jovem, muito usado em sopas, refogados e saladas. As folhas também são comestíveis e ricas em nutrientes.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 45,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Colha os nabos enquanto jovens (5-8 cm) para sabor mais suave. Os mais velhos ficam lenhosos e amargos. Use as folhas em refogados como couve.',
  },
  {
    name: 'Batata-Doce',
    scientificName: 'Ipomoea batatas',
    emoji: '🍠',
    description: 'A batata-doce é um tubérculo altamente nutritivo, rico em betacaroteno, fibras e potássio. Extremamente resistente ao calor e à seca, é fácil de cultivar no Brasil.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 120,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Propague por mudas de ramas, não por sementes. Plante em canteiros elevados e bem drenados. Quando as folhas começarem a amarelar, é hora de colher.',
  },
  {
    name: 'Alho',
    scientificName: 'Allium sativum',
    emoji: '🧄',
    description: 'O alho é um bulbo aromático fundamental na culinária mundial, com propriedades antimicrobianas e antioxidantes comprovadas. Considerado um dos alimentos medicinais mais poderosos.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 150,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Plante os dentes individuais com a ponta para cima. Quando metade das folhas estiver seca e amarela, é hora de colher. Cure em local arejado por 2 semanas.',
  },
  {
    name: 'Alho-Poró',
    scientificName: 'Allium ampeloprasum',
    emoji: '🌿',
    description: 'O alho-poró tem sabor mais suave que a cebola e o alho, sendo muito apreciado em sopas, quiches e refogados. É uma hortaliça resistente e de fácil cultivo.',
    category: PlantCategory.LEGUME,
    seasons: [Season.OUTONO, Season.INVERNO],
    harvestDays: 120,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Amontoe terra ao redor do talo branco periodicamente (blanching) para alongá-lo e torná-lo mais macio e saboroso. Colha quando o talo tiver 2-3 cm de diâmetro.',
  },
  {
    name: 'Quiabo',
    scientificName: 'Abelmoschus esculentus',
    emoji: '🌿',
    description: 'O quiabo é uma hortaliça muito resistente ao calor e à seca, indispensável na culinária mineira e baiana. Seus frutos mucilaginosos engrossam naturalmente caldos e ensopados.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 60,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Colha os frutos pequenos (7-10 cm) para textura mais macia. Frutos grandes ficam lenhosos. Use luvas ao colher pois as folhas podem irritar a pele.',
  },
  {
    name: 'Berinjela',
    scientificName: 'Solanum melongena',
    emoji: '🍆',
    description: 'A berinjela é um fruto de casca roxa brilhante, baixo em calorias e rico em antioxidantes como antocianinas. Excelente grelhada, assada ou em molhos.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 80,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Colha quando a casca estiver brilhante e firme ao toque. Berinjelas opacas estão maduras demais e ficam amargas. Instale suportes para proteger os galhos carregados.',
  },
  {
    name: 'Abóbora',
    scientificName: 'Cucurbita moschata',
    emoji: '🎃',
    description: 'A abóbora é um fruto muito cultivado e consumido no Brasil, rica em betacaroteno, potássio e vitaminas do complexo B. Extremamente versátil na culinária, do doce ao salgado.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 90,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Precisa de muito espaço para as ramas se espalharem. Quando a casca endurecer e a haste secar, é sinal de maturidade. Pode ser armazenada por meses em local fresco.',
  },
  {
    name: 'Milho',
    scientificName: 'Zea mays',
    emoji: '🌽',
    description: 'O milho é um dos cereais mais cultivados no mundo e essencial na culinária brasileira. A variedade doce é colhida verde para consumo fresco enquanto as grãos ainda estão leitosos.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 90,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Plante em blocos (não em fileiras) para garantir boa polinização cruzada pelo vento. Quando o cabelo escurecer e os grãos leitosos ao comprimir, é hora de colher.',
  },
  {
    name: 'Jiló',
    scientificName: 'Solanum gilo',
    emoji: '🟢',
    description: 'O jiló é uma hortaliça tipicamente brasileira, com sabor amargo característico que divide opiniões. Rico em ferro e vitaminas, é muito usado na culinária mineira e baiana.',
    category: PlantCategory.LEGUME,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 70,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Colha quando os frutos estiverem verdes para menor amargor. Frutos maduros ficam vermelhos e muito amargos. Planta muito resistente ao calor tropical.',
  },

  // ── FRUTAS ───────────────────────────────────────────────────────────────
  {
    name: 'Tomate',
    scientificName: 'Solanum lycopersicum',
    emoji: '🍅',
    description: 'O tomate é um dos frutos mais cultivados e consumidos no Brasil. Rico em licopeno e vitamina C, é indispensável na culinária brasileira.',
    category: PlantCategory.FRUTA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 70,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Instale estacas para apoiar as plantas. Retire os brotos axilares para concentrar energia nos galhos principais e frutos.',
  },
  {
    name: 'Morango',
    scientificName: 'Fragaria × ananassa',
    emoji: '🍓',
    description: 'O morango é uma das frutas mais populares no Brasil. Rico em vitamina C e antioxidantes, delicioso in natura, em sucos, sorvetes e confeitaria.',
    category: PlantCategory.FRUTA,
    seasons: [Season.PRIMAVERA],
    harvestDays: 90,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Use palha ao redor das plantas para evitar que os frutos apodreçam no solo. Renove as mudas a cada 2-3 anos para manter alta produtividade.',
  },
  {
    name: 'Melancia',
    scientificName: 'Citrullus lanatus',
    emoji: '🍉',
    description: 'A melancia é uma das frutas mais refrescantes do verão brasileiro, composta por 92% de água. Rica em licopeno, citrulina e vitaminas A e C.',
    category: PlantCategory.FRUTA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 90,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Bata levemente na melancia — som oco indica maturidade. A mancha amarela no solo (onde apoiou o solo) também deve ser amarela intensa. Precisa de muito espaço.',
  },
  {
    name: 'Melão',
    scientificName: 'Cucumis melo',
    emoji: '🍈',
    description: 'O melão é uma fruta de polpa doce e perfumada, muito apreciada no verão. Existem diversas variedades: amarelo, cantaloupe, galia, entre outros.',
    category: PlantCategory.FRUTA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 80,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Reduza a irrigação 2 semanas antes da colheita para concentrar os açúcares e aumentar o sabor. O aroma adocicado na casca indica que está pronto.',
  },
  {
    name: 'Maracujá',
    scientificName: 'Passiflora edulis',
    emoji: '🟡',
    description: 'O maracujá é uma fruta tropical brasileira com aroma intenso, muito usada em sucos, sobremesas e receitas culinárias. O Brasil é o maior produtor mundial.',
    category: PlantCategory.FRUTA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 180,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Precisa de suporte para crescer — treliça, cerca ou parede. Polinização manual aumenta muito a produção. Colha quando os frutos caírem naturalmente da planta.',
  },
  {
    name: 'Mamão',
    scientificName: 'Carica papaya',
    emoji: '🥭',
    description: 'O mamão é uma fruta tropical rica em papaína (enzima digestiva), vitaminas A e C e licopeno. Cresce rapidamente e produz frutos o ano todo em clima tropical.',
    category: PlantCategory.FRUTA,
    seasons: [Season.ANO_TODO],
    harvestDays: 270,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Prefere solos bem drenados — não suporta encharcamento. Existem variedades hermafroditas que não precisam de polinizadores. Muito sensível a geadas.',
  },
  {
    name: 'Banana',
    scientificName: 'Musa paradisiaca',
    emoji: '🍌',
    description: 'A banana é a fruta mais consumida no Brasil e uma das mais produzidas no mundo. Rica em potássio, carboidratos e vitaminas B6 e C. Planta de porte grande e produtiva.',
    category: PlantCategory.FRUTA,
    seasons: [Season.ANO_TODO],
    harvestDays: 365,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Plante mudas filhotes tiradas da planta mãe. Após cada colheita, corte o pseudocaule e deixe crescer um filho para a próxima produção. Precisa de muito espaço.',
  },
  {
    name: 'Abacaxi',
    scientificName: 'Ananas comosus',
    emoji: '🍍',
    description: 'O abacaxi é uma fruta tropical de sabor agridoce, rica em bromelina (enzima anti-inflamatória), vitamina C e manganês. O Brasil é um dos maiores produtores mundiais.',
    category: PlantCategory.FRUTA,
    seasons: [Season.ANO_TODO],
    harvestDays: 540,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Plante a coroa do abacaxi diretamente no solo. É extremamente resistente à seca. O fruto está maduro quando a casca começa a amarelar na base.',
  },
  {
    name: 'Goiaba',
    scientificName: 'Psidium guajava',
    emoji: '🍐',
    description: 'A goiaba é uma fruta tropical muito nutritiva, com mais vitamina C que a laranja. Pode ser consumida in natura ou usada em sucos, doces, goiabada e geleias.',
    category: PlantCategory.FRUTA,
    seasons: [Season.VERAO, Season.OUTONO],
    harvestDays: 730,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Plante a partir de mudas enxertadas para produção mais rápida e uniforme. Pode para renovação de galhos velhos. Fruta muito atraente para pássaros — proteja com redes.',
  },
  {
    name: 'Pimenta Dedo-de-Moça',
    scientificName: 'Capsicum baccatum',
    emoji: '🌶️',
    description: 'A pimenta dedo-de-moça é uma das mais populares no Brasil, com ardência moderada e sabor intenso. Muito usada em molhos, conservas e para temperar pratos.',
    category: PlantCategory.FRUTA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 90,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Quanto mais estresse hídrico (sem exagerar), mais ardida fica a pimenta. Pode ser congelada, seca ou processada em molho para conservação longa.',
  },
  {
    name: 'Limão Siciliano',
    scientificName: 'Citrus limon',
    emoji: '🍋',
    description: 'O limão siciliano tem casca amarela, polpa suculenta e sabor levemente mais suave que o limão-taiti. Muito usado em receitas, drinks e para aromatizar pratos.',
    category: PlantCategory.FRUTA,
    seasons: [Season.ANO_TODO],
    harvestDays: 540,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Colha quando a casca estiver completamente amarela. Plante em vaso grande com boa drenagem se não tiver espaço no jardim — produz bem em vasos.',
  },

  // ── ERVAS ────────────────────────────────────────────────────────────────
  {
    name: 'Manjericão',
    scientificName: 'Ocimum basilicum',
    emoji: '🌿',
    description: 'O manjericão é uma erva aromática essencial na culinária italiana e muito usada no Brasil em molhos de tomate, pestos e pratos mediterrâneos.',
    category: PlantCategory.ERVA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 60,
    wateringFreq: 'Diariamente',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Retire as flores assim que aparecerem para manter folhas com sabor mais intenso. Excelente para cultivar em vasos pequenos na cozinha.',
  },
  {
    name: 'Coentro',
    scientificName: 'Coriandrum sativum',
    emoji: '🌱',
    description: 'O coentro é uma erva aromática muito usada na culinária nordestina, em frutos do mar e na gastronomia latinoamericana e asiática.',
    category: PlantCategory.ERVA,
    seasons: [Season.OUTONO, Season.PRIMAVERA],
    harvestDays: 45,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'No calor intenso espiga rapidamente. Plante a cada 3 semanas para colheitas contínuas. As sementes (semente-de-coentro) também são usadas como especiaria.',
  },
  {
    name: 'Hortelã',
    scientificName: 'Mentha spp.',
    emoji: '🍃',
    description: 'A hortelã é uma erva de aroma refrescante muito usada em chás, sucos, drinks, pratos e medicamentos naturais. Planta extremamente resistente e produtiva.',
    category: PlantCategory.ERVA,
    seasons: [Season.ANO_TODO],
    harvestDays: 90,
    wateringFreq: 'Diariamente',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Se alastra rapidamente via estolões. Prefira cultivar em vasos para conter o crescimento. Propaga-se facilmente por estacas colocadas em água.',
  },
  {
    name: 'Alecrim',
    scientificName: 'Salvia rosmarinus',
    emoji: '🌿',
    description: 'O alecrim é uma erva mediterrânea aromática e resistente, usada em carnes assadas, pães e marinadas. Tem propriedades antioxidantes e digestivas comprovadas.',
    category: PlantCategory.ERVA,
    seasons: [Season.ANO_TODO],
    harvestDays: 90,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Tolera muito bem a seca — o excesso de água mata mais facilmente que a falta. Excelente em vasos. Propaga-se por estacas semi-lenhosas com alta taxa de sucesso.',
  },
  {
    name: 'Salsa',
    scientificName: 'Petroselinum crispum',
    emoji: '🌿',
    description: 'A salsa (salsinha) é uma erva aromática muito versátil, rica em vitaminas K, C e A. Usada como tempero e decoração em praticamente toda a culinária brasileira.',
    category: PlantCategory.ERVA,
    seasons: [Season.OUTONO, Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 75,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Germinação lenta (2-4 semanas) — tenha paciência. Colha as folhas externas mais velhas para estimular brotação contínua. Congela bem para conservação.',
  },
  {
    name: 'Cebolinha',
    scientificName: 'Allium schoenoprasum',
    emoji: '🌱',
    description: 'A cebolinha é uma erva aromática indispensável na culinária brasileira. Usada fresca como tempero em praticamente todos os pratos quentes e frios do dia a dia.',
    category: PlantCategory.ERVA,
    seasons: [Season.ANO_TODO],
    harvestDays: 60,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Corte as folhas deixando 5 cm do base para rebrote contínuo. Propaga-se por divisão de touceiras. Cresce bem em vasos pequenos na janela da cozinha.',
  },
  {
    name: 'Tomilho',
    scientificName: 'Thymus vulgaris',
    emoji: '🌿',
    description: 'O tomilho é uma erva mediterrânea de aroma intenso e persistente, muito usada em carnes, sopas, marinadas e infusões. Tem propriedades antissépticas e antioxidantes.',
    category: PlantCategory.ERVA,
    seasons: [Season.ANO_TODO],
    harvestDays: 90,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Muito resistente à seca após estabelecido. Pode de vez em quando para manter a planta compacta e produtiva. Seca facilmente para uso culinário e dura meses.',
  },
  {
    name: 'Orégano',
    scientificName: 'Origanum vulgare',
    emoji: '🌿',
    description: 'O orégano é a erva da pizza italiana e de tantos pratos mediterrâneos. Tem aroma mais intenso quando seco, e é um dos temperos mais populares no Brasil.',
    category: PlantCategory.ERVA,
    seasons: [Season.ANO_TODO],
    harvestDays: 90,
    wateringFreq: 'A cada 4 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Colha antes do florescimento para maior concentração de óleos essenciais. Seque em local arejado e escuro para preservar o aroma por até 1 ano.',
  },
  {
    name: 'Erva-Cidreira',
    scientificName: 'Melissa officinalis',
    emoji: '🍃',
    description: 'A erva-cidreira tem aroma suave de limão e é famosa pelos efeitos calmantes e ansiolíticos. Muito usada em chás, infusões, licores e culinária.',
    category: PlantCategory.ERVA,
    seasons: [Season.ANO_TODO],
    harvestDays: 80,
    wateringFreq: 'A cada 2 dias',
    sunlight: 'Sol parcial (4-6h)',
    tips: 'Pode com frequência para manter as folhas jovens e mais aromáticas. Seca-se bem para uso em chás. Atrai abelhas e outros polinizadores para o jardim.',
  },
  {
    name: 'Capim-Limão',
    scientificName: 'Cymbopogon citratus',
    emoji: '🌾',
    description: 'O capim-limão (lemongrass) tem aroma cítrico intenso, muito usado em chás, culinária asiática, drinks e como repelente natural de mosquitos e insetos.',
    category: PlantCategory.ERVA,
    seasons: [Season.ANO_TODO],
    harvestDays: 120,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Cresce em touceiras que se expandem rapidamente. Corte os talos na base. Excelente em vasos grandes. Planta perene muito resistente ao calor e à seca.',
  },
  {
    name: 'Lavanda',
    scientificName: 'Lavandula angustifolia',
    emoji: '💜',
    description: 'A lavanda é uma erva de flores violetas e aroma floral relaxante, muito usada em aromaterapia, culinária, cosméticos e como planta ornamental.',
    category: PlantCategory.ERVA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 180,
    wateringFreq: 'A cada 7 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Prefere solo bem drenado e levemente alcalino. Boa na seca mas não suporta excesso de água. Após floração, corte pela metade para estimular ramificação.',
  },
  {
    name: 'Funcho',
    scientificName: 'Foeniculum vulgare',
    emoji: '🌿',
    description: 'O funcho tem aroma e sabor anisado característicos, muito usado na culinária mediterrânea em peixes, saladas e chás digestivos. Planta alta e vistosa no jardim.',
    category: PlantCategory.ERVA,
    seasons: [Season.PRIMAVERA, Season.OUTONO],
    harvestDays: 75,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Não plante perto de endro pois cruzam e perdem o sabor característico. Folhas, sementes e o bulbo da base são todos comestíveis. Atrai borboletas e insetos benéficos.',
  },
  {
    name: 'Erva-Doce',
    scientificName: 'Pimpinella anisum',
    emoji: '🌼',
    description: 'A erva-doce tem sabor suave anisado e é muito apreciada em chás para aliviar cólicas e gases. As sementes são usadas como tempero em pães, bolos e licores.',
    category: PlantCategory.ERVA,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 90,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Colha as sementes quando as umbelas começarem a escurecer. Seque em papel por 2 semanas antes de armazenar. Planta anual que se autossemeia com facilidade.',
  },

  // ── FLORES ───────────────────────────────────────────────────────────────
  {
    name: 'Girassol',
    scientificName: 'Helianthus annuus',
    emoji: '🌻',
    description: 'O girassol é uma das flores mais emblemáticas e alegres do jardim. Suas sementes são ricas em gorduras saudáveis e vitamina E. Atrai pássaros e polinizadores.',
    category: PlantCategory.FLOR,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 80,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Plante voltado para o sul (sul-americano) para melhor exposição solar. Excelente para crianças aprenderem jardinagem. Pode atingir 2-3 metros de altura.',
  },
  {
    name: 'Calêndula',
    scientificName: 'Calendula officinalis',
    emoji: '🌼',
    description: 'A calêndula é uma flor medicinal e comestível, com propriedades cicatrizantes e anti-inflamatórias. Suas pétalas laranja e amarelas são usadas em saladas, chás e cosméticos naturais.',
    category: PlantCategory.FLOR,
    seasons: [Season.OUTONO, Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 50,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Retire as flores murchas regularmente (deadheading) para estimular brotamento contínuo por meses. Excelente companheira na horta — repele pragas como pulgões e nematoides.',
  },
  {
    name: 'Cravo-de-Defunto',
    scientificName: 'Tagetes erecta',
    emoji: '🌸',
    description: 'Apesar do nome, o cravo-de-defunto é uma linda flor amarela e laranja muito usada em jardins e como repelente natural de pragas na horta, especialmente nematoides.',
    category: PlantCategory.FLOR,
    seasons: [Season.ANO_TODO],
    harvestDays: 60,
    wateringFreq: 'A cada 3 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Plante ao redor ou entre as hortaliças para protegê-las de pestes. As flores são comestíveis e ricas em luteína. Excelente para bordaduras e vasos decorativos.',
  },
  {
    name: 'Gerânio',
    scientificName: 'Pelargonium spp.',
    emoji: '🌺',
    description: 'O gerânio é uma das plantas ornamentais mais populares do Brasil, com flores coloridas e algumas variedades com folhas perfumadas. Muito resistente e de fácil manutenção.',
    category: PlantCategory.FLOR,
    seasons: [Season.ANO_TODO],
    harvestDays: 90,
    wateringFreq: 'A cada 4 dias',
    sunlight: 'Pleno sol (4-6h)',
    tips: 'Retire flores murchas para estimular novas. Propaga-se facilmente por estacas. Ótimo para vasos em janelas, sacadas e jardins suspensos.',
  },
  {
    name: 'Violeta Africana',
    scientificName: 'Saintpaulia ionantha',
    emoji: '💜',
    description: 'A violeta africana é uma das plantas de interior mais amadas, com flores delicadas em tons de violeta, rosa e branco. Ideal para ambientes internos com luz indireta.',
    category: PlantCategory.FLOR,
    seasons: [Season.ANO_TODO],
    harvestDays: 90,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Sol indireto (sem sol direto)',
    tips: 'Regue sempre pelo prato, nunca direto nas folhas — manchas escuras se formam. Gira o vaso periodicamente para crescimento uniforme. Adube mensalmente com fertilizante para floríferas.',
  },
  {
    name: 'Cosmos',
    scientificName: 'Cosmos bipinnatus',
    emoji: '🌸',
    description: 'O cosmos é uma flor delicada e graciosa com pétalas em rosa, branco e vermelho. Floresce abundantemente e é excelente para atrair borboletas e abelhas ao jardim.',
    category: PlantCategory.FLOR,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 70,
    wateringFreq: 'A cada 4 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Ironicamente cresce melhor em solos pobres — fertilização excessiva produz muita folhagem e poucas flores. Ótima para corte. Autossemeia abundantemente.',
  },

  // ── ÁRVORES ──────────────────────────────────────────────────────────────
  {
    name: 'Limoeiro',
    scientificName: 'Citrus × latifolia',
    emoji: '🍋',
    description: 'O limoeiro-taiti é o mais cultivado no Brasil, produzindo frutos sem sementes e muito suculentos. Produz frutos o ano todo em clima tropical e pode ser cultivado em vasos grandes.',
    category: PlantCategory.ARVORE,
    seasons: [Season.ANO_TODO],
    harvestDays: 730,
    wateringFreq: 'A cada 4 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Plante em solo bem drenado. Adube com fertilizante NPK e micronutrientes (especialmente zinco e manganês). Pode levemente após a colheita para renovar galhos produtivos.',
  },
  {
    name: 'Laranjeira',
    scientificName: 'Citrus sinensis',
    emoji: '🍊',
    description: 'A laranjeira produz frutos ricos em vitamina C, flavonoides e antioxidantes. No Brasil se produz desde a variedade Pera até a Bahia, Lima e Valencia.',
    category: PlantCategory.ARVORE,
    seasons: [Season.INVERNO, Season.PRIMAVERA],
    harvestDays: 730,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Prefira mudas enxertadas sobre porta-enxertos resistentes. Adube 3-4 vezes ao ano com fertilizante específico para citrus. A coloração laranja da casca depende de noites frescas.',
  },
  {
    name: 'Abacateiro',
    scientificName: 'Persea americana',
    emoji: '🥑',
    description: 'O abacateiro produz frutos ricos em gorduras monoinsaturadas saudáveis, vitaminas e minerais. Árvore grande e longeva, pode produzir por décadas.',
    category: PlantCategory.ARVORE,
    seasons: [Season.VERAO, Season.OUTONO],
    harvestDays: 1095,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Prefere mudas enxertadas para produção mais rápida e uniforme. Plante dois indivíduos de tipos A e B para melhor polinização cruzada. Não tolera solos encharcados.',
  },
  {
    name: 'Pitangueira',
    scientificName: 'Eugenia uniflora',
    emoji: '🔴',
    description: 'A pitangueira é uma árvore frutífera nativa do Brasil, produtora de frutos vermelhos e aromáticos com sabor agridoce único. Rica em vitaminas e antioxidantes.',
    category: PlantCategory.ARVORE,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 730,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Planta nativa muito resistente e adaptada ao clima brasileiro. Produz abundantemente quando bem nutrida. Colha as pitangas vermelho-escuras ou arroxeadas para máxima doçura.',
  },
  {
    name: 'Jabuticabeira',
    scientificName: 'Plinia cauliflora',
    emoji: '🫐',
    description: 'A jabuticabeira é uma árvore frutífera brasileira única, com frutos roxos que nascem diretamente no tronco e nos galhos. Os frutos são deliciosos in natura e fazem licores famosos.',
    category: PlantCategory.ARVORE,
    seasons: [Season.PRIMAVERA, Season.VERAO],
    harvestDays: 1825,
    wateringFreq: 'A cada 5 dias',
    sunlight: 'Pleno sol (6-8h)',
    tips: 'Crescimento lento mas longevidade enorme — pode viver 100 anos ou mais. Vale cada ano de espera. Os frutos devem ser colhidos imediatamente quando maduros pois fermentam rápido.',
  },
  {
    name: 'Aceroleira',
    scientificName: 'Malpighia emarginata',
    emoji: '🍒',
    description: 'A aceroleira produz frutos vermelhos riquíssimos em vitamina C — cada acerola tem até 30 vezes mais vitamina C que uma laranja! Muito fácil de cultivar no Brasil.',
    category: PlantCategory.ARVORE,
    seasons: [Season.ANO_TODO],
    harvestDays: 365,
    wateringFreq: 'A cada 4 dias',
    sunlight: 'Pleno sol (8h+)',
    tips: 'Planta muito rústica e resistente, produz o ano todo em clima quente. Pode para renovar e manter altura manejável. Os frutos amadurecem rápido — consuma em 2-3 dias da colheita.',
  },
]

async function main() {
  console.log('🌱 Iniciando seed do banco de dados...\n')

  const existingNames = new Set(
    (await prisma.plant.findMany({ select: { name: true } })).map((p) => p.name),
  )

  const newPlants = plants.filter((p) => !existingNames.has(p.name))

  if (newPlants.length === 0) {
    console.log(`✅ Todas as ${plants.length} plantas já estão no banco. Nada a fazer.`)
    return
  }

  for (const plant of newPlants) {
    await prisma.plant.create({ data: plant })
    console.log(`  ✓ ${plant.emoji} ${plant.name}`)
  }

  const total = await prisma.plant.count()
  console.log(`\n✅ Seed concluído! ${newPlants.length} plantas inseridas. Total no banco: ${total}.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
